# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build without Tests
      run: mvn clean package -DskipTests

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/jaejaeproject:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/jaejaeproject:latest

    - name: SSH to Server and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          # 최신 이미지를 pull
          docker pull ${{ secrets.DOCKER_USERNAME }}/jaejaeproject:latest  # 커밋 SHA를 활용한 태그 사용
    
          # 이미지 업데이트
          docker-compose -f /home/ubuntu/docker-compose.yml pull
    
          # 새로운 이미지를 사용해 컨테이너를 시작, 기존 컨테이너를 종료하지 않음
          docker-compose -f /home/ubuntu/docker-compose.yml up -d --no-deps jeckjeck  # "app" 서비스만 업데이트
    
          # 불필요한 이미지를 정리
          docker image prune -f
